/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemporadasRouteImport } from './routes/temporadas'
import { Route as TareasModuloRouteImport } from './routes/tareas-modulo'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PresenciaRouteImport } from './routes/presencia'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as PlanificacionRouteImport } from './routes/planificacion'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ClubRouteImport } from './routes/club'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TareasIndexRouteImport } from './routes/tareas.index'
import { Route as ScoutingIndexRouteImport } from './routes/scouting.index'
import { Route as PartidosIndexRouteImport } from './routes/partidos.index'
import { Route as EstadisticasIndexRouteImport } from './routes/estadisticas.index'
import { Route as EquipoIndexRouteImport } from './routes/equipo.index'
import { Route as EntrenamientosIndexRouteImport } from './routes/entrenamientos.index'
import { Route as AnalisisIndexRouteImport } from './routes/analisis.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TareasNuevaRouteImport } from './routes/tareas.nueva'
import { Route as ScoutingNuevoRouteImport } from './routes/scouting.nuevo'
import { Route as ScoutingClipIdRouteImport } from './routes/scouting.$clipId'
import { Route as PartidosPostRouteImport } from './routes/partidos.post'
import { Route as EquipoTeamIdRouteImport } from './routes/equipo.$teamId'
import { Route as EntrenamientosNuevoRouteImport } from './routes/entrenamientos.nuevo'
import { Route as EntrenamientosSessionIdRouteImport } from './routes/entrenamientos.$sessionId'
import { Route as AuthVerifyPendingRouteImport } from './routes/auth.verify-pending'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthPendingApprovalRouteImport } from './routes/auth.pending-approval'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AnalisisNuevoRouteImport } from './routes/analisis.nuevo'
import { Route as AnalisisCategoriasRouteImport } from './routes/analisis.categorias'
import { Route as AnalisisVideoIdRouteImport } from './routes/analisis.$videoId'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminMigracionRouteImport } from './routes/admin.migracion'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLimitesRouteImport } from './routes/admin.limites'
import { Route as AdminAsignacionesRouteImport } from './routes/admin.asignaciones'
import { Route as PartidosLiveIndexRouteImport } from './routes/partidos.live.index'
import { Route as TareasTaskIdEditarRouteImport } from './routes/tareas.$taskId.editar'
import { Route as ScoutingClipIdEditarRouteImport } from './routes/scouting.$clipId.editar'
import { Route as PartidosLiveNuevoRouteImport } from './routes/partidos.live.nuevo'
import { Route as PartidosLiveLiveIdRouteImport } from './routes/partidos.live.$liveId'
import { Route as EstadisticasJugadorPlayerIdRouteImport } from './routes/estadisticas.jugador.$playerId'
import { Route as EstadisticasEquipoTeamIdRouteImport } from './routes/estadisticas.equipo.$teamId'
import { Route as EntrenamientosSessionIdEditarRouteImport } from './routes/entrenamientos.$sessionId.editar'

const TemporadasRoute = TemporadasRouteImport.update({
  id: '/temporadas',
  path: '/temporadas',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasModuloRoute = TareasModuloRouteImport.update({
  id: '/tareas-modulo',
  path: '/tareas-modulo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenciaRoute = PresenciaRouteImport.update({
  id: '/presencia',
  path: '/presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificacionRoute = PlanificacionRouteImport.update({
  id: '/planificacion',
  path: '/planificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasIndexRoute = TareasIndexRouteImport.update({
  id: '/tareas/',
  path: '/tareas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingIndexRoute = ScoutingIndexRouteImport.update({
  id: '/scouting/',
  path: '/scouting/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosIndexRoute = PartidosIndexRouteImport.update({
  id: '/partidos/',
  path: '/partidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasIndexRoute = EstadisticasIndexRouteImport.update({
  id: '/estadisticas/',
  path: '/estadisticas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoIndexRoute = EquipoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipoRoute,
} as any)
const EntrenamientosIndexRoute = EntrenamientosIndexRouteImport.update({
  id: '/entrenamientos/',
  path: '/entrenamientos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisIndexRoute = AnalisisIndexRouteImport.update({
  id: '/analisis/',
  path: '/analisis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TareasNuevaRoute = TareasNuevaRouteImport.update({
  id: '/tareas/nueva',
  path: '/tareas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingNuevoRoute = ScoutingNuevoRouteImport.update({
  id: '/scouting/nuevo',
  path: '/scouting/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingClipIdRoute = ScoutingClipIdRouteImport.update({
  id: '/scouting/$clipId',
  path: '/scouting/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosPostRoute = PartidosPostRouteImport.update({
  id: '/partidos/post',
  path: '/partidos/post',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoTeamIdRoute = EquipoTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => EquipoRoute,
} as any)
const EntrenamientosNuevoRoute = EntrenamientosNuevoRouteImport.update({
  id: '/entrenamientos/nuevo',
  path: '/entrenamientos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenamientosSessionIdRoute = EntrenamientosSessionIdRouteImport.update({
  id: '/entrenamientos/$sessionId',
  path: '/entrenamientos/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyPendingRoute = AuthVerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPendingApprovalRoute = AuthPendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AnalisisNuevoRoute = AnalisisNuevoRouteImport.update({
  id: '/analisis/nuevo',
  path: '/analisis/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisCategoriasRoute = AnalisisCategoriasRouteImport.update({
  id: '/analisis/categorias',
  path: '/analisis/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisVideoIdRoute = AnalisisVideoIdRouteImport.update({
  id: '/analisis/$videoId',
  path: '/analisis/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMigracionRoute = AdminMigracionRouteImport.update({
  id: '/migracion',
  path: '/migracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLimitesRoute = AdminLimitesRouteImport.update({
  id: '/limites',
  path: '/limites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAsignacionesRoute = AdminAsignacionesRouteImport.update({
  id: '/asignaciones',
  path: '/asignaciones',
  getParentRoute: () => AdminRoute,
} as any)
const PartidosLiveIndexRoute = PartidosLiveIndexRouteImport.update({
  id: '/partidos/live/',
  path: '/partidos/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasTaskIdEditarRoute = TareasTaskIdEditarRouteImport.update({
  id: '/tareas/$taskId/editar',
  path: '/tareas/$taskId/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingClipIdEditarRoute = ScoutingClipIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ScoutingClipIdRoute,
} as any)
const PartidosLiveNuevoRoute = PartidosLiveNuevoRouteImport.update({
  id: '/partidos/live/nuevo',
  path: '/partidos/live/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidosLiveLiveIdRoute = PartidosLiveLiveIdRouteImport.update({
  id: '/partidos/live/$liveId',
  path: '/partidos/live/$liveId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasJugadorPlayerIdRoute =
  EstadisticasJugadorPlayerIdRouteImport.update({
    id: '/estadisticas/jugador/$playerId',
    path: '/estadisticas/jugador/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstadisticasEquipoTeamIdRoute =
  EstadisticasEquipoTeamIdRouteImport.update({
    id: '/estadisticas/equipo/$teamId',
    path: '/estadisticas/equipo/$teamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntrenamientosSessionIdEditarRoute =
  EntrenamientosSessionIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => EntrenamientosSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/club': typeof ClubRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRouteWithChildren
  '/planificacion': typeof PlanificacionRoute
  '/plataforma': typeof PlataformaRoute
  '/presencia': typeof PresenciaRoute
  '/privacidad': typeof PrivacidadRoute
  '/tareas-modulo': typeof TareasModuloRoute
  '/temporadas': typeof TemporadasRoute
  '/admin/asignaciones': typeof AdminAsignacionesRoute
  '/admin/limites': typeof AdminLimitesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/migracion': typeof AdminMigracionRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/analisis/$videoId': typeof AnalisisVideoIdRoute
  '/analisis/categorias': typeof AnalisisCategoriasRoute
  '/analisis/nuevo': typeof AnalisisNuevoRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/entrenamientos/$sessionId': typeof EntrenamientosSessionIdRouteWithChildren
  '/entrenamientos/nuevo': typeof EntrenamientosNuevoRoute
  '/equipo/$teamId': typeof EquipoTeamIdRoute
  '/partidos/post': typeof PartidosPostRoute
  '/scouting/$clipId': typeof ScoutingClipIdRouteWithChildren
  '/scouting/nuevo': typeof ScoutingNuevoRoute
  '/tareas/nueva': typeof TareasNuevaRoute
  '/admin/': typeof AdminIndexRoute
  '/analisis/': typeof AnalisisIndexRoute
  '/entrenamientos/': typeof EntrenamientosIndexRoute
  '/equipo/': typeof EquipoIndexRoute
  '/estadisticas/': typeof EstadisticasIndexRoute
  '/partidos/': typeof PartidosIndexRoute
  '/scouting/': typeof ScoutingIndexRoute
  '/tareas/': typeof TareasIndexRoute
  '/entrenamientos/$sessionId/editar': typeof EntrenamientosSessionIdEditarRoute
  '/estadisticas/equipo/$teamId': typeof EstadisticasEquipoTeamIdRoute
  '/estadisticas/jugador/$playerId': typeof EstadisticasJugadorPlayerIdRoute
  '/partidos/live/$liveId': typeof PartidosLiveLiveIdRoute
  '/partidos/live/nuevo': typeof PartidosLiveNuevoRoute
  '/scouting/$clipId/editar': typeof ScoutingClipIdEditarRoute
  '/tareas/$taskId/editar': typeof TareasTaskIdEditarRoute
  '/partidos/live/': typeof PartidosLiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/club': typeof ClubRoute
  '/configuracion': typeof ConfiguracionRoute
  '/planificacion': typeof PlanificacionRoute
  '/plataforma': typeof PlataformaRoute
  '/presencia': typeof PresenciaRoute
  '/privacidad': typeof PrivacidadRoute
  '/tareas-modulo': typeof TareasModuloRoute
  '/temporadas': typeof TemporadasRoute
  '/admin/asignaciones': typeof AdminAsignacionesRoute
  '/admin/limites': typeof AdminLimitesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/migracion': typeof AdminMigracionRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/analisis/$videoId': typeof AnalisisVideoIdRoute
  '/analisis/categorias': typeof AnalisisCategoriasRoute
  '/analisis/nuevo': typeof AnalisisNuevoRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/entrenamientos/$sessionId': typeof EntrenamientosSessionIdRouteWithChildren
  '/entrenamientos/nuevo': typeof EntrenamientosNuevoRoute
  '/equipo/$teamId': typeof EquipoTeamIdRoute
  '/partidos/post': typeof PartidosPostRoute
  '/scouting/$clipId': typeof ScoutingClipIdRouteWithChildren
  '/scouting/nuevo': typeof ScoutingNuevoRoute
  '/tareas/nueva': typeof TareasNuevaRoute
  '/admin': typeof AdminIndexRoute
  '/analisis': typeof AnalisisIndexRoute
  '/entrenamientos': typeof EntrenamientosIndexRoute
  '/equipo': typeof EquipoIndexRoute
  '/estadisticas': typeof EstadisticasIndexRoute
  '/partidos': typeof PartidosIndexRoute
  '/scouting': typeof ScoutingIndexRoute
  '/tareas': typeof TareasIndexRoute
  '/entrenamientos/$sessionId/editar': typeof EntrenamientosSessionIdEditarRoute
  '/estadisticas/equipo/$teamId': typeof EstadisticasEquipoTeamIdRoute
  '/estadisticas/jugador/$playerId': typeof EstadisticasJugadorPlayerIdRoute
  '/partidos/live/$liveId': typeof PartidosLiveLiveIdRoute
  '/partidos/live/nuevo': typeof PartidosLiveNuevoRoute
  '/scouting/$clipId/editar': typeof ScoutingClipIdEditarRoute
  '/tareas/$taskId/editar': typeof TareasTaskIdEditarRoute
  '/partidos/live': typeof PartidosLiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/club': typeof ClubRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRouteWithChildren
  '/planificacion': typeof PlanificacionRoute
  '/plataforma': typeof PlataformaRoute
  '/presencia': typeof PresenciaRoute
  '/privacidad': typeof PrivacidadRoute
  '/tareas-modulo': typeof TareasModuloRoute
  '/temporadas': typeof TemporadasRoute
  '/admin/asignaciones': typeof AdminAsignacionesRoute
  '/admin/limites': typeof AdminLimitesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/migracion': typeof AdminMigracionRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/analisis/$videoId': typeof AnalisisVideoIdRoute
  '/analisis/categorias': typeof AnalisisCategoriasRoute
  '/analisis/nuevo': typeof AnalisisNuevoRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/entrenamientos/$sessionId': typeof EntrenamientosSessionIdRouteWithChildren
  '/entrenamientos/nuevo': typeof EntrenamientosNuevoRoute
  '/equipo/$teamId': typeof EquipoTeamIdRoute
  '/partidos/post': typeof PartidosPostRoute
  '/scouting/$clipId': typeof ScoutingClipIdRouteWithChildren
  '/scouting/nuevo': typeof ScoutingNuevoRoute
  '/tareas/nueva': typeof TareasNuevaRoute
  '/admin/': typeof AdminIndexRoute
  '/analisis/': typeof AnalisisIndexRoute
  '/entrenamientos/': typeof EntrenamientosIndexRoute
  '/equipo/': typeof EquipoIndexRoute
  '/estadisticas/': typeof EstadisticasIndexRoute
  '/partidos/': typeof PartidosIndexRoute
  '/scouting/': typeof ScoutingIndexRoute
  '/tareas/': typeof TareasIndexRoute
  '/entrenamientos/$sessionId/editar': typeof EntrenamientosSessionIdEditarRoute
  '/estadisticas/equipo/$teamId': typeof EstadisticasEquipoTeamIdRoute
  '/estadisticas/jugador/$playerId': typeof EstadisticasJugadorPlayerIdRoute
  '/partidos/live/$liveId': typeof PartidosLiveLiveIdRoute
  '/partidos/live/nuevo': typeof PartidosLiveNuevoRoute
  '/scouting/$clipId/editar': typeof ScoutingClipIdEditarRoute
  '/tareas/$taskId/editar': typeof TareasTaskIdEditarRoute
  '/partidos/live/': typeof PartidosLiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/club'
    | '/configuracion'
    | '/equipo'
    | '/planificacion'
    | '/plataforma'
    | '/presencia'
    | '/privacidad'
    | '/tareas-modulo'
    | '/temporadas'
    | '/admin/asignaciones'
    | '/admin/limites'
    | '/admin/logs'
    | '/admin/migracion'
    | '/admin/modulos'
    | '/analisis/$videoId'
    | '/analisis/categorias'
    | '/analisis/nuevo'
    | '/auth/forgot'
    | '/auth/pending-approval'
    | '/auth/reset'
    | '/auth/verify-pending'
    | '/entrenamientos/$sessionId'
    | '/entrenamientos/nuevo'
    | '/equipo/$teamId'
    | '/partidos/post'
    | '/scouting/$clipId'
    | '/scouting/nuevo'
    | '/tareas/nueva'
    | '/admin/'
    | '/analisis/'
    | '/entrenamientos/'
    | '/equipo/'
    | '/estadisticas/'
    | '/partidos/'
    | '/scouting/'
    | '/tareas/'
    | '/entrenamientos/$sessionId/editar'
    | '/estadisticas/equipo/$teamId'
    | '/estadisticas/jugador/$playerId'
    | '/partidos/live/$liveId'
    | '/partidos/live/nuevo'
    | '/scouting/$clipId/editar'
    | '/tareas/$taskId/editar'
    | '/partidos/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/club'
    | '/configuracion'
    | '/planificacion'
    | '/plataforma'
    | '/presencia'
    | '/privacidad'
    | '/tareas-modulo'
    | '/temporadas'
    | '/admin/asignaciones'
    | '/admin/limites'
    | '/admin/logs'
    | '/admin/migracion'
    | '/admin/modulos'
    | '/analisis/$videoId'
    | '/analisis/categorias'
    | '/analisis/nuevo'
    | '/auth/forgot'
    | '/auth/pending-approval'
    | '/auth/reset'
    | '/auth/verify-pending'
    | '/entrenamientos/$sessionId'
    | '/entrenamientos/nuevo'
    | '/equipo/$teamId'
    | '/partidos/post'
    | '/scouting/$clipId'
    | '/scouting/nuevo'
    | '/tareas/nueva'
    | '/admin'
    | '/analisis'
    | '/entrenamientos'
    | '/equipo'
    | '/estadisticas'
    | '/partidos'
    | '/scouting'
    | '/tareas'
    | '/entrenamientos/$sessionId/editar'
    | '/estadisticas/equipo/$teamId'
    | '/estadisticas/jugador/$playerId'
    | '/partidos/live/$liveId'
    | '/partidos/live/nuevo'
    | '/scouting/$clipId/editar'
    | '/tareas/$taskId/editar'
    | '/partidos/live'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buscar'
    | '/club'
    | '/configuracion'
    | '/equipo'
    | '/planificacion'
    | '/plataforma'
    | '/presencia'
    | '/privacidad'
    | '/tareas-modulo'
    | '/temporadas'
    | '/admin/asignaciones'
    | '/admin/limites'
    | '/admin/logs'
    | '/admin/migracion'
    | '/admin/modulos'
    | '/analisis/$videoId'
    | '/analisis/categorias'
    | '/analisis/nuevo'
    | '/auth/forgot'
    | '/auth/pending-approval'
    | '/auth/reset'
    | '/auth/verify-pending'
    | '/entrenamientos/$sessionId'
    | '/entrenamientos/nuevo'
    | '/equipo/$teamId'
    | '/partidos/post'
    | '/scouting/$clipId'
    | '/scouting/nuevo'
    | '/tareas/nueva'
    | '/admin/'
    | '/analisis/'
    | '/entrenamientos/'
    | '/equipo/'
    | '/estadisticas/'
    | '/partidos/'
    | '/scouting/'
    | '/tareas/'
    | '/entrenamientos/$sessionId/editar'
    | '/estadisticas/equipo/$teamId'
    | '/estadisticas/jugador/$playerId'
    | '/partidos/live/$liveId'
    | '/partidos/live/nuevo'
    | '/scouting/$clipId/editar'
    | '/tareas/$taskId/editar'
    | '/partidos/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  ClubRoute: typeof ClubRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EquipoRoute: typeof EquipoRouteWithChildren
  PlanificacionRoute: typeof PlanificacionRoute
  PlataformaRoute: typeof PlataformaRoute
  PresenciaRoute: typeof PresenciaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TareasModuloRoute: typeof TareasModuloRoute
  TemporadasRoute: typeof TemporadasRoute
  AnalisisVideoIdRoute: typeof AnalisisVideoIdRoute
  AnalisisCategoriasRoute: typeof AnalisisCategoriasRoute
  AnalisisNuevoRoute: typeof AnalisisNuevoRoute
  EntrenamientosSessionIdRoute: typeof EntrenamientosSessionIdRouteWithChildren
  EntrenamientosNuevoRoute: typeof EntrenamientosNuevoRoute
  PartidosPostRoute: typeof PartidosPostRoute
  ScoutingClipIdRoute: typeof ScoutingClipIdRouteWithChildren
  ScoutingNuevoRoute: typeof ScoutingNuevoRoute
  TareasNuevaRoute: typeof TareasNuevaRoute
  AnalisisIndexRoute: typeof AnalisisIndexRoute
  EntrenamientosIndexRoute: typeof EntrenamientosIndexRoute
  EstadisticasIndexRoute: typeof EstadisticasIndexRoute
  PartidosIndexRoute: typeof PartidosIndexRoute
  ScoutingIndexRoute: typeof ScoutingIndexRoute
  TareasIndexRoute: typeof TareasIndexRoute
  EstadisticasEquipoTeamIdRoute: typeof EstadisticasEquipoTeamIdRoute
  EstadisticasJugadorPlayerIdRoute: typeof EstadisticasJugadorPlayerIdRoute
  PartidosLiveLiveIdRoute: typeof PartidosLiveLiveIdRoute
  PartidosLiveNuevoRoute: typeof PartidosLiveNuevoRoute
  TareasTaskIdEditarRoute: typeof TareasTaskIdEditarRoute
  PartidosLiveIndexRoute: typeof PartidosLiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temporadas': {
      id: '/temporadas'
      path: '/temporadas'
      fullPath: '/temporadas'
      preLoaderRoute: typeof TemporadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas-modulo': {
      id: '/tareas-modulo'
      path: '/tareas-modulo'
      fullPath: '/tareas-modulo'
      preLoaderRoute: typeof TareasModuloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presencia': {
      id: '/presencia'
      path: '/presencia'
      fullPath: '/presencia'
      preLoaderRoute: typeof PresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planificacion': {
      id: '/planificacion'
      path: '/planificacion'
      fullPath: '/planificacion'
      preLoaderRoute: typeof PlanificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas/': {
      id: '/tareas/'
      path: '/tareas'
      fullPath: '/tareas/'
      preLoaderRoute: typeof TareasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/': {
      id: '/scouting/'
      path: '/scouting'
      fullPath: '/scouting/'
      preLoaderRoute: typeof ScoutingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos/': {
      id: '/partidos/'
      path: '/partidos'
      fullPath: '/partidos/'
      preLoaderRoute: typeof PartidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/': {
      id: '/estadisticas/'
      path: '/estadisticas'
      fullPath: '/estadisticas/'
      preLoaderRoute: typeof EstadisticasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/': {
      id: '/equipo/'
      path: '/'
      fullPath: '/equipo/'
      preLoaderRoute: typeof EquipoIndexRouteImport
      parentRoute: typeof EquipoRoute
    }
    '/entrenamientos/': {
      id: '/entrenamientos/'
      path: '/entrenamientos'
      fullPath: '/entrenamientos/'
      preLoaderRoute: typeof EntrenamientosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis/': {
      id: '/analisis/'
      path: '/analisis'
      fullPath: '/analisis/'
      preLoaderRoute: typeof AnalisisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tareas/nueva': {
      id: '/tareas/nueva'
      path: '/tareas/nueva'
      fullPath: '/tareas/nueva'
      preLoaderRoute: typeof TareasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/nuevo': {
      id: '/scouting/nuevo'
      path: '/scouting/nuevo'
      fullPath: '/scouting/nuevo'
      preLoaderRoute: typeof ScoutingNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/$clipId': {
      id: '/scouting/$clipId'
      path: '/scouting/$clipId'
      fullPath: '/scouting/$clipId'
      preLoaderRoute: typeof ScoutingClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos/post': {
      id: '/partidos/post'
      path: '/partidos/post'
      fullPath: '/partidos/post'
      preLoaderRoute: typeof PartidosPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/$teamId': {
      id: '/equipo/$teamId'
      path: '/$teamId'
      fullPath: '/equipo/$teamId'
      preLoaderRoute: typeof EquipoTeamIdRouteImport
      parentRoute: typeof EquipoRoute
    }
    '/entrenamientos/nuevo': {
      id: '/entrenamientos/nuevo'
      path: '/entrenamientos/nuevo'
      fullPath: '/entrenamientos/nuevo'
      preLoaderRoute: typeof EntrenamientosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenamientos/$sessionId': {
      id: '/entrenamientos/$sessionId'
      path: '/entrenamientos/$sessionId'
      fullPath: '/entrenamientos/$sessionId'
      preLoaderRoute: typeof EntrenamientosSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-pending': {
      id: '/auth/verify-pending'
      path: '/verify-pending'
      fullPath: '/auth/verify-pending'
      preLoaderRoute: typeof AuthVerifyPendingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/pending-approval': {
      id: '/auth/pending-approval'
      path: '/pending-approval'
      fullPath: '/auth/pending-approval'
      preLoaderRoute: typeof AuthPendingApprovalRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/analisis/nuevo': {
      id: '/analisis/nuevo'
      path: '/analisis/nuevo'
      fullPath: '/analisis/nuevo'
      preLoaderRoute: typeof AnalisisNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis/categorias': {
      id: '/analisis/categorias'
      path: '/analisis/categorias'
      fullPath: '/analisis/categorias'
      preLoaderRoute: typeof AnalisisCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis/$videoId': {
      id: '/analisis/$videoId'
      path: '/analisis/$videoId'
      fullPath: '/analisis/$videoId'
      preLoaderRoute: typeof AnalisisVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/migracion': {
      id: '/admin/migracion'
      path: '/migracion'
      fullPath: '/admin/migracion'
      preLoaderRoute: typeof AdminMigracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/limites': {
      id: '/admin/limites'
      path: '/limites'
      fullPath: '/admin/limites'
      preLoaderRoute: typeof AdminLimitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/asignaciones': {
      id: '/admin/asignaciones'
      path: '/asignaciones'
      fullPath: '/admin/asignaciones'
      preLoaderRoute: typeof AdminAsignacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/partidos/live/': {
      id: '/partidos/live/'
      path: '/partidos/live'
      fullPath: '/partidos/live/'
      preLoaderRoute: typeof PartidosLiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas/$taskId/editar': {
      id: '/tareas/$taskId/editar'
      path: '/tareas/$taskId/editar'
      fullPath: '/tareas/$taskId/editar'
      preLoaderRoute: typeof TareasTaskIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/$clipId/editar': {
      id: '/scouting/$clipId/editar'
      path: '/editar'
      fullPath: '/scouting/$clipId/editar'
      preLoaderRoute: typeof ScoutingClipIdEditarRouteImport
      parentRoute: typeof ScoutingClipIdRoute
    }
    '/partidos/live/nuevo': {
      id: '/partidos/live/nuevo'
      path: '/partidos/live/nuevo'
      fullPath: '/partidos/live/nuevo'
      preLoaderRoute: typeof PartidosLiveNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidos/live/$liveId': {
      id: '/partidos/live/$liveId'
      path: '/partidos/live/$liveId'
      fullPath: '/partidos/live/$liveId'
      preLoaderRoute: typeof PartidosLiveLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/jugador/$playerId': {
      id: '/estadisticas/jugador/$playerId'
      path: '/estadisticas/jugador/$playerId'
      fullPath: '/estadisticas/jugador/$playerId'
      preLoaderRoute: typeof EstadisticasJugadorPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/equipo/$teamId': {
      id: '/estadisticas/equipo/$teamId'
      path: '/estadisticas/equipo/$teamId'
      fullPath: '/estadisticas/equipo/$teamId'
      preLoaderRoute: typeof EstadisticasEquipoTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenamientos/$sessionId/editar': {
      id: '/entrenamientos/$sessionId/editar'
      path: '/editar'
      fullPath: '/entrenamientos/$sessionId/editar'
      preLoaderRoute: typeof EntrenamientosSessionIdEditarRouteImport
      parentRoute: typeof EntrenamientosSessionIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAsignacionesRoute: typeof AdminAsignacionesRoute
  AdminLimitesRoute: typeof AdminLimitesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMigracionRoute: typeof AdminMigracionRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAsignacionesRoute: AdminAsignacionesRoute,
  AdminLimitesRoute: AdminLimitesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMigracionRoute: AdminMigracionRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthPendingApprovalRoute: typeof AuthPendingApprovalRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyPendingRoute: typeof AuthVerifyPendingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthPendingApprovalRoute: AuthPendingApprovalRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyPendingRoute: AuthVerifyPendingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EquipoRouteChildren {
  EquipoTeamIdRoute: typeof EquipoTeamIdRoute
  EquipoIndexRoute: typeof EquipoIndexRoute
}

const EquipoRouteChildren: EquipoRouteChildren = {
  EquipoTeamIdRoute: EquipoTeamIdRoute,
  EquipoIndexRoute: EquipoIndexRoute,
}

const EquipoRouteWithChildren =
  EquipoRoute._addFileChildren(EquipoRouteChildren)

interface EntrenamientosSessionIdRouteChildren {
  EntrenamientosSessionIdEditarRoute: typeof EntrenamientosSessionIdEditarRoute
}

const EntrenamientosSessionIdRouteChildren: EntrenamientosSessionIdRouteChildren =
  {
    EntrenamientosSessionIdEditarRoute: EntrenamientosSessionIdEditarRoute,
  }

const EntrenamientosSessionIdRouteWithChildren =
  EntrenamientosSessionIdRoute._addFileChildren(
    EntrenamientosSessionIdRouteChildren,
  )

interface ScoutingClipIdRouteChildren {
  ScoutingClipIdEditarRoute: typeof ScoutingClipIdEditarRoute
}

const ScoutingClipIdRouteChildren: ScoutingClipIdRouteChildren = {
  ScoutingClipIdEditarRoute: ScoutingClipIdEditarRoute,
}

const ScoutingClipIdRouteWithChildren = ScoutingClipIdRoute._addFileChildren(
  ScoutingClipIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BuscarRoute: BuscarRoute,
  ClubRoute: ClubRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EquipoRoute: EquipoRouteWithChildren,
  PlanificacionRoute: PlanificacionRoute,
  PlataformaRoute: PlataformaRoute,
  PresenciaRoute: PresenciaRoute,
  PrivacidadRoute: PrivacidadRoute,
  TareasModuloRoute: TareasModuloRoute,
  TemporadasRoute: TemporadasRoute,
  AnalisisVideoIdRoute: AnalisisVideoIdRoute,
  AnalisisCategoriasRoute: AnalisisCategoriasRoute,
  AnalisisNuevoRoute: AnalisisNuevoRoute,
  EntrenamientosSessionIdRoute: EntrenamientosSessionIdRouteWithChildren,
  EntrenamientosNuevoRoute: EntrenamientosNuevoRoute,
  PartidosPostRoute: PartidosPostRoute,
  ScoutingClipIdRoute: ScoutingClipIdRouteWithChildren,
  ScoutingNuevoRoute: ScoutingNuevoRoute,
  TareasNuevaRoute: TareasNuevaRoute,
  AnalisisIndexRoute: AnalisisIndexRoute,
  EntrenamientosIndexRoute: EntrenamientosIndexRoute,
  EstadisticasIndexRoute: EstadisticasIndexRoute,
  PartidosIndexRoute: PartidosIndexRoute,
  ScoutingIndexRoute: ScoutingIndexRoute,
  TareasIndexRoute: TareasIndexRoute,
  EstadisticasEquipoTeamIdRoute: EstadisticasEquipoTeamIdRoute,
  EstadisticasJugadorPlayerIdRoute: EstadisticasJugadorPlayerIdRoute,
  PartidosLiveLiveIdRoute: PartidosLiveLiveIdRoute,
  PartidosLiveNuevoRoute: PartidosLiveNuevoRoute,
  TareasTaskIdEditarRoute: TareasTaskIdEditarRoute,
  PartidosLiveIndexRoute: PartidosLiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
